rm: cannot remove '/media/leavador/DATA/DSP_hw3/7/studir/r07922156/dsp_hw3_r07922156/bigram.lm': No such file or directory
rm: cannot remove '/media/leavador/DATA/DSP_hw3/7/studir/r07922156/dsp_hw3_r07922156/trigram.lm': No such file or directory
rm: cannot remove '/media/leavador/DATA/DSP_hw3/7/studir/r07922156/dsp_hw3_r07922156/Big5-ZhuYin.map': No such file or directory
rm: cannot remove '/media/leavador/DATA/DSP_hw3/7/studir/r07922156/dsp_hw3_r07922156/ta': No such file or directory
Traceback (most recent call last):
  File "ta/compare_map.py", line 28, in <module>
    initial = tokens[0]
IndexError: list index out of range
bigram.lm: line 9: warning: non-zero probability for <unk> in closed-vocabulary LM
Aborted (core dumped)
bigram.lm: line 9: warning: non-zero probability for <unk> in closed-vocabulary LM
Aborted (core dumped)
bigram.lm: line 9: warning: non-zero probability for <unk> in closed-vocabulary LM
Aborted (core dumped)
bigram.lm: line 9: warning: non-zero probability for <unk> in closed-vocabulary LM
Aborted (core dumped)
bigram.lm: line 9: warning: non-zero probability for <unk> in closed-vocabulary LM
Aborted (core dumped)
bigram.lm: line 9: warning: non-zero probability for <unk> in closed-vocabulary LM
Aborted (core dumped)
bigram.lm: line 9: warning: non-zero probability for <unk> in closed-vocabulary LM
Aborted (core dumped)
bigram.lm: line 9: warning: non-zero probability for <unk> in closed-vocabulary LM
Aborted (core dumped)
bigram.lm: line 9: warning: non-zero probability for <unk> in closed-vocabulary LM
Aborted (core dumped)
bigram.lm: line 9: warning: non-zero probability for <unk> in closed-vocabulary LM
Aborted (core dumped)
make: *** [run] Error 134
Traceback (most recent call last):
  File "ta/compare_result.py", line 41, in <module>
    total_distance += edit_distance( TA_ZhuYin[i] , STU_ZhuYin[i] )
IndexError: list index out of range
Traceback (most recent call last):
  File "ta/compare_result.py", line 41, in <module>
    total_distance += edit_distance( TA_ZhuYin[i] , STU_ZhuYin[i] )
IndexError: list index out of range
Traceback (most recent call last):
  File "ta/compare_result.py", line 41, in <module>
    total_distance += edit_distance( TA_ZhuYin[i] , STU_ZhuYin[i] )
IndexError: list index out of range
Traceback (most recent call last):
  File "ta/compare_result.py", line 41, in <module>
    total_distance += edit_distance( TA_ZhuYin[i] , STU_ZhuYin[i] )
IndexError: list index out of range
Traceback (most recent call last):
  File "ta/compare_result.py", line 41, in <module>
    total_distance += edit_distance( TA_ZhuYin[i] , STU_ZhuYin[i] )
IndexError: list index out of range
Traceback (most recent call last):
  File "ta/compare_result.py", line 41, in <module>
    total_distance += edit_distance( TA_ZhuYin[i] , STU_ZhuYin[i] )
IndexError: list index out of range
Traceback (most recent call last):
  File "ta/compare_result.py", line 41, in <module>
    total_distance += edit_distance( TA_ZhuYin[i] , STU_ZhuYin[i] )
IndexError: list index out of range
Traceback (most recent call last):
  File "ta/compare_result.py", line 41, in <module>
    total_distance += edit_distance( TA_ZhuYin[i] , STU_ZhuYin[i] )
IndexError: list index out of range
Traceback (most recent call last):
  File "ta/compare_result.py", line 41, in <module>
    total_distance += edit_distance( TA_ZhuYin[i] , STU_ZhuYin[i] )
IndexError: list index out of range
Traceback (most recent call last):
  File "ta/compare_result.py", line 41, in <module>
    total_distance += edit_distance( TA_ZhuYin[i] , STU_ZhuYin[i] )
IndexError: list index out of range
